### ISSUE TITLE
Errors associated to setting security context values

### ISSUE THREAD

**Issue by Caroline132** [opencost/opencost-helm-chart#104]
**Description**
There are errors when attempting to enable the security context for the UI (commented out in the [values.yaml](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L217) file). The specific settings causing the errors are as follows:
- `securityContext.capabilities.drop: ALL`
- `securityContext.runAsNonRoot: true`
- `securityContext.runAsUser: 1000`
- `securityContext.readOnlyRootFilesystem: true`

1. Setting`securityContext.capabilities.drop: ALL` leads to a _CrashLoopBackOff_ error with the message:
![image](https://github.com/opencost/opencost-helm-chart/assets/20731423/e90269ed-15b1-4edf-8e94-181dca896731)

2. Setting `securityContext.runAsNonRoot: true` leads to a _CreateContainerConfigError_ with the message:
![image](https://github.com/opencost/opencost-helm-chart/assets/20731423/244a16f2-e04c-4322-9e59-a101a534a507)

3. Setting `securityContext.runAsUser: 1000` leads to a _CrashLoopBackOff_ error with the message:
![image](https://github.com/opencost/opencost-helm-chart/assets/20731423/113c821a-de46-4d24-9451-341e28d6eabd)

4. Setting `securityContext.readOnlyRootFilesystem: true` leads to a _CrashLoopBackOff_ error with the message (this also occurs in the exporter):
![image](https://github.com/opencost/opencost-helm-chart/assets/20731423/739f68c9-32b4-4f83-add1-b244c8e3088f)

Also, version 1.105 of OpenCost apparently [enabled the UI image to run as non-root](https://github.com/opencost/opencost/pull/1947) by setting the user as 1001. However, by default it still runs as root. Also, when we set the chart value of `runAsNonRoot` to true for opencost-ui, it's still running as root (the same thing occurs when `runAsUser` is additionally set to 1001 with `runAsNonRoot` to true):
![image](https://github.com/umple/AcademicTeamManagement/assets/20731423/fb5ad386-e8a1-4634-b638-94de9a20ed38)
![image](https://github.com/umple/AcademicTeamManagement/assets/20731423/1f7e1d86-fd2b-46d6-a504-9715c4fb4a26)

**Reproduction Steps**
Install the Helm chart (observed in latest release 1.18.0) with the security context settings mentioned above.
Observe the errors described above occurring in the pod logs.

**Expected Behavior**
I expect the security context settings to be enabled without causing these errors, as they are intended to enhance container security.

**Comment by dnskr** [comment]
We experience the same issue in OpenShift environment.
OpenShift cluster sets `runAsUser` value to some high random UID number (for example 1000620000) and the user with the UID cannot write to `/var/www/` path becauce the directory owned by `1001` user/group.
It should be fixed somehow to be able to run `opencost-ui` container with anonymous user.

**Comment by mattray** [comment]
https://github.com/opencost/opencost/pull/2130 has been merged, it reportedly fixes OpenShift UI permissions but won't be in a release until 1.107 most likely.

**Comment by mattray** [comment]
https://github.com/opencost/opencost/releases/tag/v1.106.1 fixed the UI container running as root, it shouldn't be an issue anymore.

**Comment by jemag** [comment]
I believe this issue is still relevant since the commented out securityContext is still non-working as reported by the author, @mattray.

`readOnlyRootFilesystem: true` still cannot be set because `sed` is trying to update the js files in `/var/www` from the `docker-entrypoint.sh` and `runAsUser` should be set to `1001` I believe.
